### ISSUE TITLE
Current limitation and trace width

### ISSUE THREAD

**Issue by olli177** [clusterzx/MultiController_PCB#2]
Following this calculation for the heating of PCB traces:

[ I[A] / (K x h[mm]^0,5 x b[mm]^0,64) ] ^2= ΔT[K] with K = 3,3 for 2-Layer PCBs and 2,25A as current value I[A]

The PCB trace of VBUS would heat up to ΔT[K] = 40 °C for 35um and ΔT[K] = 20°C for 70um

Idea: Increasing trace width to 0.5mm or even more would decrease the thermal heating by 10°C.

**Comment by Knochi** [comment]
High Current paths track width increased to 0.6mm for VBus, 12V and +5V.
